import '../models/game.dart';

final List<Game> initialGames = [
  Game(
    name: "Animal Well",
    category: "Indie Game",
    rating: 85.0,
    honor: "2024 TGA Best Indie Game Nominee",
    imagePath: "assets/AnimalWell.png",
    isIndie: true,
    steamLink: "https://store.steampowered.com/app/813230/ANIMAL_WELL/",
  ),
  Game(
    name: "Astro Bot",
    category: "Action Adventure",
    rating: 94.0,
    honor: "2024 TGA Game of the Year",
    imagePath: "assets/AstroBot.png",
    isIndie: false,
    steamLink: null,
  ),
  Game(
    name: "Balatro",
    category: "Strategy Card Game",
    rating: 88.0,
    honor: "2024 TGA Best Indie Game",
    imagePath: "assets/Balatro.png",
    isIndie: true,
    steamLink: "https://store.steampowered.com/app/2379780/Balatro/",
  ),
  Game(
    name: "Black Myth: Wukong",
    category: "Action RPG",
    rating: 81.0,
    honor: "2024 TGA Best Action Game",
    imagePath: "assets/BlackMythWukong.png",
    isIndie: false,
    steamLink: "https://store.steampowered.com/app/2358720/_/",
  ),
  Game(
    name: "Dragon Age: The Veilguard",
    category: "RPG",
    rating: 90.0,
    honor: "2024 TGA Best RPG Nominee",
    imagePath: "assets/DragonAgeTheVeliguard.png",
    isIndie: false,
    steamLink: "https://store.steampowered.com/agecheck/app/1845910/",
  ),
  Game(
    name: "Final Fantasy VII Rebirth",
    category: "RPG",
    rating: 93.0,
    honor: "2024 TGA Best Narrative",
    imagePath: "assets/FinalFantasyVIIRe.png",
    isIndie: false,
    steamLink:
        "https://store.steampowered.com/app/2909400/FINAL_FANTASY_VII_REBIRTH/",
  ),
  Game(
    name: "Frostpunk 2",
    category: "Strategy Simulation",
    rating: 87.0,
    honor: "2024 TGA Best Strategy/Simulation Game Nominee",
    imagePath: "assets/FrostPunk2.png",
    isIndie: false,
    steamLink: "https://store.steampowered.com/app/1601000/Frostpunk_2/",
  ),
  Game(
    name: "Infinity Nikki",
    category: "Adventure",
    rating: 80.0,
    honor: "2024 IGN Best Game Nominee",
    imagePath: "assets/InfinityNikki.png",
    isIndie: true,
    steamLink: null,
  ),
  Game(
    name: "Like a Dragon 8",
    category: "Action RPG",
    rating: 86.0,
    honor: "2024 TGA Best Action/Adventure Game Nominee",
    imagePath: "assets/LikeADragon8.png",
    isIndie: false,
    steamLink: null,
  ),
  Game(
    name: "Metaphor: ReFantazio",
    category: "RPG",
    rating: 89.0,
    honor: "2024 TGA Best RPG",
    imagePath: "assets/ReFantazio.png",
    isIndie: false,
    steamLink:
        "https://store.steampowered.com/app/2395690/Metaphor_ReFantazio/",
  ),
  Game(
    name: "Tekken 8",
    category: "Fighting Game",
    rating: 88.0,
    honor: "2024 TGA Best Fighting Game",
    imagePath: "assets/Tekken8.png",
    isIndie: false,
    steamLink: null,
  ),
  Game(
    name: "The Legend of Zelda: Echoes of Wisdom",
    category: "Action Adventure",
    rating: 95.0,
    honor: "2024 TGA Best Game Direction",
    imagePath: "assets/ZeldaEchoofWisdom.png",
    isIndie: false,
    steamLink: null,
  ),
];
